apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftlink-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftlink-backend
  template:
    metadata:
      labels:
        app: giftlink-backend
    spec:
      containers:
        - name: giftlink-backend
          image: mark62005/giftlink-backend:latest
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: giftlink-backend-secrets
