apiVersion: v1
kind: Service
metadata:
  name: giftlink-backend-service
spec:
  selector:
    app: giftlink-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
