name: "CI/CD"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Set up Environment Variables
        run: echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" >> $GITHUB_ENV
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

      - name: Install Dependencies
        run: |
          cd client
          pnpm install

      - name: Build client
        run: |
          cd client
          pnpm run build
          echo "Frontend build successfully"
